import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "@/styles/app.css"
import Header from "@/components/layout/Header";

const firaSans = Fira_Sans({
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Azure Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${firaSans.className} antialiased`}
      >
        <Header />
        <main className="container mt-32">
        {children}
        </main>
      </body>
    </html>
  );
}
