import type { Metadata } from "next";
import { Fira_Sans, Fira_Mono } from "next/font/google";
import "@/styles/app.css"
import Header from "@/components/layout/Header";

const firaSans = Fira_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const firaMono = Fira_Mono({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Azure Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${firaSans.className} ${firaMono.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
